name: Github Actions

on:
  push:
    branches:
      - "master"
      - "feature/*" #matches feature/Ads and feature/dsC but not feature/sdsd/sds
      - "feature/**" # matche with any number of / feature/sdsd/sds
      - "!features/featC"
    tags:
      - "v1.*"
    #paths:
    #  - "**.js"
    paths-ignore:
      - "*.docx"
      - "!**.js"
      
#on: 
  #push:

  #pull_request:
  #  types:
  #    - opened
  #    - assigned
  #    - closed

#on: 
  #schedule:
  #  - cron: "0/5 * * * *"

    # https://crontab.guru/
    # minute  -- hour -- day(of month) -- month -- day(of week)
    # * any value
    # , value list seperator
    # - range of values
    # / step values
    # @yearly @anually @montly (non standard)


#on:
#  repository_dispatch:
#    types: [build]
    #import requests
    #import json

    #url = "https://api.github.com/repos/raghrv/github-actions-test/dispatches"

    #payload = json.dumps({
    #  "event_type": "build"
    #})
    #headers = {
    #  'Accept': 'application/vnd.github.v3+json',
    #  'Authorization': 'Basic OmdocF9aVTlLY1c1MHlBQ2d6MmY5Yms4d09CWkVGTHhEbWYyQVFQS1u=',
    #  'Content-Type': 'application/json',
    #  'Cookie': '_octo=GH1.1.608399341.1623677039; logged_in=no'
    #}

    #response = requests.request("POST", url, headers=headers, data=payload)
    #print(response.text)

jobs:
  running-github-js-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo GITHUB_SHA $GITHUB_SHA
          echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
          echo GITHUB_WORKSPACE $GITHUB_WORKSPACE
          echo "git token ${{ github.token }}"
      - name: Checkout
        #https://github.com/actions/checkout#usage
        uses: actions/checkout@v1
      - name: List After Checkout
        run: | 
          pwd
          ls -a 
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 
            Raghav
      - name: Greeting time
        run: echo "Greeting Time:${{ steps.greet.outputs.time }}"
        