name: Shell Commands

on: [pull_request]

jobs:
  job-run-shell-commnad:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello Actions 1"
      
      - name: Multiline script
        run: |
          echo "Hello" 
          node -v
          npm -v

