name: Shell Commands

on: [push, pull_request]

jobs:
  job-run-shell-commnad:
    runs-on: ubuntu-latest
    steps:
      - name: Bash Shell - Echo a string
        run: echo "Hello Actions 1"
      
      - name: Bash Shell - Multiline script
        run: |
          echo "Hello" 
          node -v
          npm -v
      - name: Python Shell Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  job-windows-shell-command:
    runs-on: windows-latest
    steps:
      - name: Get working Dir
        run: Get-Location
      - name: Get Shell Working Dir
        run: pwd
        shell: bash
      - name: Python Get working dir
        run: |
          import os
          print(os.getcwd())
        shell: python